### ISSUE TITLE
Webinterface

### ISSUE THREAD

**Issue by franky384** [max2play/webinterface#1]
Das updaten des max2play webinterfaces überschreibt jedesmal die lxpanel konfiguration im homeordner des angemeldeten users  und setzt den Besitzer auf root. Bitte ändern !!Das updaten des max2play webinterfaces überschreibt jedesmal die lxpanel konfiguration im homeordner des angemeldeten users  und setzt den Besitzer auf root. Bitte ändern !!

**Comment by max2play** [comment]
Danke für die Info! Die lxpanel Datei wird beim nächsten Update nicht mehr dabei sein - damit ist das Problem gelöst.
