### ISSUE TITLE
[INFO] Docker?

### ISSUE THREAD

**Issue by neurocis** [max2play/webinterface#3]
Hopefully I have the time to do this, but I have forked this repo w/intent of adding hypriot docker as an add-in and framework for future plugins.

Ref:
[Hypriot Blog](http://blog.hypriot.com)
[Hypriot Github](https://github.com/hypriot)

Thoughts? Anybody else interested in this effort?

**Comment by max2play** [comment]
Sounds interesting! Once you finish your work we can add the plugin to our website - this makes it easy to find and to install for others.
If you need assistance or have questions related to the add-in development just send me a message.
