### ISSUE TITLE
can't make squeezelite with new script

### ISSUE THREAD

**Issue by ghost** [max2play/webinterface#4]
hi,
I have odroid xu4 and debian jessie. I am not able to make makefile.m2p. Here is log

root@max2play:~/squeezelite# make -f Makefile.m2p
cc -Wall -fPIC -s -O3 -march=armv6 -mfloat-abi=hard -mfpu=vfp -DRESAMPLE -DCONTROLSBS -DALSASYNC -DBLUETOOTHSYNC -DFFMPEG -DVISEXPORT -DDSD -DGPIO -DIR -DRPI -I./include main.c -c -o main.o
In file included from /usr/include/stdio.h:934:0,
                 from squeezelite.h:234,
                 from main.c:30:
/usr/include/arm-linux-gnueabihf/bits/stdio.h: In function ‘vprintf’:
/usr/include/arm-linux-gnueabihf/bits/stdio.h:37:1: sorry, unimplemented: Thumb-1 hard-float VFP ABI
 {
 ^
Makefile.m2p:20: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by max2play** [comment]
Hi,
can you try to edit the Makefile and remove the -DRPI option and the -DGPIO option as this refers to the Raspberry Pi.
