### ISSUE TITLE
setting dnla gmediarender GMEDIARENDERER_ALSA_DEVICE and GMEDIARENDER_ALSA_DEVICE is confused

### ISSUE THREAD

**Issue by linuxlurak** [max2play/webinterface#6]
In /etc/init.d/gmediarender the variable "GMEDIARENDER**ER**_ALSA_DEVICE" is grepped from
/opt/max2play/audioplayer.conf where actually GMEDIARENDER_ALSA_DEVICE is defined. 

Therefore audio output of gmediarender is not set / not set correctly. In my case always to --gstout-audiosink=alsasink --gstout-audiodevice=sysdefault.

**Comment by max2play** [comment]
Hi,
you can change the soundcard on the audioplayer tab of the webinterface. This changes the parameter in the audioplayer.conf file. Did you try this?

**Comment by linuxlurak** [comment]
It's nothing that changes by choosing the device. As stated: There are two different variables defined. The one is called "GMEDIARENDER**ER**_ALSA_DEVICE" (caveat: additional ER in **the variables name**) and the other variable is called "GMEDIARENDER_ALSA_DEVICE". 

It's actually _not_ about the content of the variable (that you can change on the audioplayer tab). 

The name of the variable is called different in /opt/max2play/audioplayer.conf and in /etc/init.d/gmediarender. Once with an additional "ER" in the variables name.

Cheers!

**Comment by max2play** [comment]
OK - got it - sorry but I did not see the "ER" in the first message. Fixed this in the current BETA. 

Thanks a lot for your help on fixing this issue!

All the Best
