### ISSUE TITLE
Inconsistent use of SSL during updates

### ISSUE THREAD

**Issue by gcrow** [max2play/webinterface#7]
When updating, only the first download is secured via HTTPS.  This should occur for all the plugins.  Output below.

`
Running Check for Plugin Updates and install if available
Update IQAudIO (https://shop.max2play.com/media/downloadable/currentversion/iqaudio.tar): Click here to show detailed information
Serverversion: 2019-07-04T14:18:01+0000
lokale Version:2019-06-18T14:30:01+0100
Get Plugin from https://shop.max2play.com/media/downloadable/currentversion/iqaudio.tar
Load Plugin from tar
Installing Plugin iqaudio
Install successful

Update Jivelite (http://shop.max2play.com/media/downloadable/currentversion/jivelite.tar): Click here to show detailed information
Serverversion: 2019-07-04T14:17:51+0000
lokale Version:2019-06-18T14:29:51+0100
Get Plugin from http://shop.max2play.com/media/downloadable/currentversion/jivelite.tar
Load Plugin from tar
Installing Plugin jivelite
Install successful

Update Raspberry Settings (http://shop.max2play.com/media/downloadable/currentversion/raspberrysettings.tar): Click here to show detailed information
Serverversion: 2019-07-04T14:17:55+0000
lokale Version:2019-06-18T14:29:55+0100
Get Plugin from http://shop.max2play.com/media/downloadable/currentversion/raspberrysettings.tar
Load Plugin from tar
Installing Plugin raspberrysettings
Install successful

Update Bluetooth (http://shop.max2play.com/media/downloadable/currentversion/bluetooth.tar): Click here to show detailed information
Serverversion: 2019-07-04T14:18:11+0000
lokale Version:2019-06-18T14:30:10+0100
Get Plugin from http://shop.max2play.com/media/downloadable/currentversion/bluetooth.tar
Load Plugin from tar
Installing Plugin bluetooth
Install successful

Update Spotify Connect (http://shop.max2play.com/media/downloadable/currentversion/spotifyconnect.tar): Click here to show detailed information
Serverversion: 2019-07-04T14:18:18+0000
lokale Version:2019-06-18T14:30:17+0100
Get Plugin from http://shop.max2play.com/media/downloadable/currentversion/spotifyconnect.tar
Load Plugin from tar
Installing Plugin spotifyconnect
Install successful

Update Music Player MPD (http://shop.max2play.com/media/downloadable/currentversion/mpd.tar): Click here to show detailed information
Serverversion: 2019-07-04T14:18:04+0000
lokale Version:2019-06-18T14:30:03+0100
Get Plugin from http://shop.max2play.com/media/downloadable/currentversion/mpd.tar
Load Plugin from tar
Installing Plugin mpd
Install successful

Max2Play update started
Click here to show detailed information
`

**Comment by max2play** [comment]
Hi gcrow,
thanks for your report! 
Although no personal data is transfered, I will address this issue with the next update and force all requests to shop.max2play.com to be https.
